{% set version = "2.0.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: genozip
  version: {{ version }}

source:
  url: https://github.com/divonlan/genozip/archive/genozip-{{ version }}.tar.gz
  sha256: ca62fdea92962121f62faca8e9b67078a0b04c2a37be74bba081844d0305e34b
 
build:
  skip: True  # [win]
  number: 0

requirements:
  build:    
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - bzip2
  host:
    - {{native}}gcc-libs         # [win]
    - zlib
    - bzip2
  run:
    - {{native}}gcc-libs         # [win]
    - zlib
    - bzip2

test:
  source_files: 
    - test-file.vcf

  commands:
    {% set genozip_executables = [
      "genozip",
      "genounzip",
      "genocat",
      "genols"
    ] %}
    {% for executable in genozip_executables %}
    - test -f ${PREFIX}/bin/{{ executable }}  # [unix]
    {% endfor %}
    - which genozip.exe  # [win]
    - genozip --password abc --test test-file.vcf 2>&1  

    extra:
  recipe-maintainers:
    - divonlan
   
about:
  home: https://github.com/divonlan/genozip
  dev_url: https://github.com/divonlan/genozip
  license: CUSTOM
  license_family: OTHER
  license_file: 
    - LICENSE.non-commercial.txt
    - LICENSE.commercial.txt
  summary: Compressor for VCF genomic files, up to 5x better than gzip and faster too
  description: |
test test
