{% set version = "14.0.23" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: genozip
  version: {{ version }}

source:
  url: https://github.com/divonlan/genozip/archive/genozip-{{ version }}.tar.gz
  sha256: 7e6d03da896dcba3ee06a5cd26919721151640ebb1701d391b6dbbd59043aa10
 
build:
  skip: True  # [win]
  number: 0

requirements:
  build:    
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
  host:
    - {{native}}gcc-libs         # [win]
  run:
    - {{native}}gcc-libs         # [win]
    - curl

test:

  commands:
    {% set genozip_executables = [
      "genozip",
      "genounzip",
      "genocat",
      "genols"
    ] %}
    - genozip --version

about:
  home: https://genozip.com
  dev_url: https://github.com/divonlan/genozip
  doc_url: https://genozip.com
  license: CUSTOM
  license_family: OTHER
  license_file: 
    - LICENSE.txt
  summary: Compressor for genomic files (FASTQ, BAM, VCF, FASTA and more), up to 5x better than gzip and faster too
  description: |

extra:
  recipe-maintainers:
    - divonlan
