{% set version = "2.1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: genozip
  version: {{ version }}

source:
  url: https://github.com/divonlan/genozip/archive/genozip-{{ version }}.tar.gz
  sha256: 4d16b1d5b5e5e369895089672cdca16b08eaa11913a63120b63ea684343c00ce
 
build:
  skip: True  # [win]
  number: 0

requirements:
  build:    
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - bzip2
  host:
    - {{native}}gcc-libs         # [win]
    - zlib
    - bzip2
  run:
    - {{native}}gcc-libs         # [win]
    - zlib
    - bzip2

test:
  source_files: 
    - test-file.vcf

  commands:
    {% set genozip_executables = [
      "genozip",
      "genounzip",
      "genocat",
      "genols"
    ] %}
    {% for executable in genozip_executables %}
    - test -f ${PREFIX}/bin/{{ executable }}  # [unix]
    {% endfor %}
    - which genozip.exe  # [win]
    - genozip --password abc --test test-file.vcf 2>&1  

about:
  home: https://github.com/divonlan/genozip
  dev_url: https://github.com/divonlan/genozip
  license: CUSTOM
  license_family: OTHER
  license_file: 
    - LICENSE.non-commercial.txt
    - LICENSE.commercial.txt
  summary: Compressor for VCF genomic files, up to 5x better than gzip and faster too
  description: |
    genozip
    genozip is a compressor for VCF genomic files (it compresses .vcf or .vcf.gz or .vcf.bz2 files).
    
    It achieves x2 to x5 better compression ratios than gzip because it leverages some properties of the genomic data, such as linkage disequilibrium, to compress better. It is also a lot faster than gzip.
    
    The compression is lossless - the decompressed VCF file is 100% identical to the original VCF file.
    
    The command line options are similar to gzip and bcftools, so if you're familiar with these, it works pretty much the same. To get started, try: genozip --help
    
    Commands: 
    genozip   - compress one or more files 
    genounzip - decompress one or more files 
    genols    - show metadata of files or the entire directory 
    genocat   - view one or more files 
    
    Some advanced options:
    
    Lookups:
    genocat -r ^Y,MT file1.vcf       -- displays all chromosomes except Y and MT
    genocat -r -10000 file1.vcf      -- displays positions up to 10000
    genocat -s SMPL1,SMPL2 file1.vcf -- displays 2 samples
    Note: there is no need for a separate indexing step or index file
    
    Concatenating & splitting:
    genozip file1.vcf file2.vcf -o concat.vcf.genozip 
    genounzip concat.vcf.genozip -O 
    
    Calculating the MD5 of the VCF file:
    genozip file.vcf --md5 
    genols file.vcf.genozip --md5 
    Note: the MD5 is always calculated under the hood in genozip, and automatically verified during genounzip 
    
    Encryption:
    genozip file.vcf --password abc 
    
    Feature requests and bug reports: bugs@genozip.com 
    
    genozip is free for non-commercial use. For a commercial license, please contact sales@genozip.com 
    
    Usage is subject to terms and conditions. The license can be viewed with genozip --license
    
    THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

extra:
  recipe-maintainers:
    - divonlan
