{% set version = "15.0.50" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: genozip
  version: {{ version }}

source:
  url: https://github.com/divonlan/genozip/archive/genozip-{{ version }}.tar.gz
  sha256: 9011870e80d0e2c1b72391b34b817a9bd6079e92a29ac7f0a17de8402aa4377d
 
build:
  skip: True  # [win]
  number: 0

requirements:
  build:    
    - {{posix}}make
    - nasm
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
  host:
    - {{native}}gcc-libs         # [win]
  run:
    - {{native}}gcc-libs         # [win]
    - curl

test:
  commands:
    - genozip --version          # [not win]
    - genozip.exe --version      # [win]

about:
  home: https://genozip.com
  dev_url: https://github.com/divonlan/genozip
  doc_url: https://genozip.com
  license: CUSTOM
  license_family: OTHER
  license_file: 
    - LICENSE.txt
  summary: Compressor for genomic files (FASTQ, BAM, VCF, FASTA and more), up to 5x better than gzip and faster too
  description: |

extra:
  recipe-maintainers:
    - divonlan
