{% set version = "13.0.15" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: genozip
  version: {{ version }}

source:
  url: https://github.com/divonlan/genozip/archive/genozip-{{ version }}.tar.gz
  sha256: 3ec3ad789ac865122c56bf8eae4f77e8124575771c675a8520e1ce3aaa9a94a9
 
build:
  skip: True  # [win]
  number: 0

requirements:
  build:    
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
  host:
    - {{native}}gcc-libs         # [win]
  run:
    - {{native}}gcc-libs         # [win]
    - curl

test:

  commands:
    {% set genozip_executables = [
      "genozip",
      "genounzip",
      "genocat",
      "genols"
    ] %}
    - genozip --help

about:
  home: https://genozip.com
  dev_url: https://github.com/divonlan/genozip
  doc_url: https://genozip.com
  license: CUSTOM
  license_family: OTHER
  license_file: 
    - LICENSE.txt
  summary: Compressor for genomic files (FASTQ, BAM, VCF, FASTA and more), up to 5x better than gzip and faster too
  description: |
    
    Genozip
    
    Genozip is also available on Conda and binary downloads. For additional installation options, See: https://genozip.com
    
    Genozip is a compressor for BAM, FASTQ, VCF and other genomic files - see https://genozip.com
    
    For Illumina data .bam and .fastq.gz files, the typical gain over gzip is around 4X. For PacBio and Oxford Nanopore data aligned .bam files, the gain is typically around 2X. For .vcf.gz files, the gain over gzip is typically 3-6X. Here are some examples: https://genozip.com/benchmarks.html.
    
    Yes, Genozip can compress already-compressed files (.gz .bz2 .xz .bam .cram). 
     
    The compression is lossless - the decompressed file is 100% identical to the original file (see documentation for exceptions). 
    
    Genozip is free for academic and training use (as defined in the license). For use with data generated in a clinical or commercial settings, please see https://genozip.com/commercial.html or contact sales@genozip.com 
    
    Usage is subject to terms and conditions. The license can be viewed on https://genozip.com/license.html
    
    THIS SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS, COPYRIGHT HOLDERS OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

extra:
  recipe-maintainers:
    - divonlan
