{% set version = "15.0.61" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: genozip
  version: {{ version }}

source:
  url: https://github.com/divonlan/genozip/archive/genozip-{{ version }}.tar.gz
  sha256: 7d84bb75c1790e262880c8172c0afd152c19fcd2509ee94a2f31e77052e76f7a
 
build:
  # Selector (e.g [win]) list: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors
  # Windows builds & tests successfully, but then the test fails in Appveyor - it seems the executable is not loading (maybe missing gcc libraries? just a hunch)
  skip: True  # [win]
  number: 0

requirements:
  build:    
    - {{ posix }}make
    - nasm                       # [not arm64]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
  host:
    - {{ native }}gcc-libs       # [win]
  run:
    - {{ native }}gcc-libs       # [win]
    - curl 

test:
  commands:
    - genozip --version          # [not win]
    - genozip.exe --version      # [win]

about:
  home: https://genozip.com
  dev_url: https://github.com/divonlan/genozip
  doc_url: https://genozip.com
  license: CUSTOM
  license_family: OTHER
  license_file: 
    - LICENSE.txt
  summary: Compressor for genomic files (FASTQ, BAM, VCF, FASTA and more), up to 5x better than gzip and faster too
  description: |
    
    [![Current Release](https://img.shields.io/github/v/release/divonlan/genozip "Current Release")](https://github.com/divonlan/genozip/releases/latest) [![Conda Downloads](https://img.shields.io/conda/dn/conda-forge/genozip?label=Conda%20Downloads&style=flat-square)](https://anaconda.org/conda-forge/genozip)
    
    Genozip
    
    Genozip is a lossless compressor for  FASTQ, BAM/CRAM, VCF and <a href="https://www.genozip.com/compression">many other genomic files - see https://genozip.com
    
    Genozip is also available on Conda and binary downloads, see <a href="https://genozip.com/installing">installation options.
    
    Building from source: make -j (required for building: gcc 8.5 or above ; nasm).
    
    New: <a href="https://genozip.com">Genozip 15 - with Deep™ - losslessly co-compressing BAM and FASTQ files:
    
    ![v15 deep benchmark](https://github.com/divonlan/genozip/assets/56345591/39c7e9c5-135d-49c9-9213-89d4b830842a)
    
    Genozip Genozip is a commercial product, but we make it free for certain academic research use. See <a href="https://genozip.com/get-genozip">eligibility and other licensing options or contact <a href="mailto://sales@genozip.com">sales@genozip.com 
    
    IMPORTANT: Genozip is a commercial product, NOT AN OPEN SOURCE product - we provide our source code to assure users that they will always have access to the code needed to decompress their files. HOWEVER, reverse engineering, code modifications, derivative works or inclusion of the code or parts thereof into other software packages is strictly forbidden by the <a href="https://genozip.com/license">license.
    
    Attributions for 3rd party source components: <a href="https://genozip.com/attributions">attributions.
    
    THIS SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS, COPYRIGHT HOLDERS OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

extra:
  recipe-maintainers:
    - divonlan
