conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
build_platform:
    linux_64: linux_64
    osx_arm64: osx_arm64
#    win_64: win_64
